// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class _001700180019DistConcFreg
{
    public string? Id { get; set; }

    public string? Distrito { get; set; }

    public string? Id2 { get; set; }

    public string? Concelho { get; set; }

    public string? Id3 { get; set; }

    public string? Freguesia { get; set; }

    public DateTime? UpdatedAt { get; set; }
}