// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class _00330040Condecoraco
{
    public string? IdTipo { get; set; }

    public string? DescricaoTipo { get; set; }

    public string? AbreviaturaTipo { get; set; }

    public string? IdMedalha { get; set; }

    public string? DescricaoMedalha { get; set; }

    public string? AbreviaturaMedalha { get; set; }

    public DateTime? UpdatedAt { get; set; }
}