// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class _00380039GrupoEmpregado
{
    public string? IdGp { get; set; }

    public string? DescricaoGp { get; set; }

    public string? AbreviaturaGp { get; set; }

    public string? IdSgp { get; set; }

    public string? DescricaoSgp { get; set; }

    public string? AbreviaturaSgp { get; set; }

    public DateTime? UpdatedAt { get; set; }
}