// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class _0034TiposContigenciasAusencia
{
    public string? Begda { get; set; }

    public string? Endda { get; set; }

    public string? Id { get; set; }

    public string? Descricao { get; set; }

    public string? Abreviatura { get; set; }

    public string? V1 { get; set; }

    public string? V2 { get; set; }

    public DateTime? UpdatedAt { get; set; }
}