// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class _0077007800790080NivelSalarial
{
    public string? IdTipoTarifa { get; set; }

    public string? DescricaoTipoTarifa { get; set; }

    public string? IdRegiaoColetivo { get; set; }

    public string? DescricaoRegiaoColetivo { get; set; }

    public string? IdFaixaSalarial { get; set; }

    public string? IdNivelSalarial { get; set; }

    public DateTime? UpdatedAt { get; set; }
}