// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsIdentifIdentificacao
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Tipodoc { get; set; }

    public string? Tipodocdesc { get; set; }

    public string? Numdocid { get; set; }

    public string? Autemiss { get; set; }

    public string? Dtemissao { get; set; }

    public string? Dtvalidade { get; set; }

    public string? Paisemiss { get; set; }

    public string? ZzdispId { get; set; }

    public DateTime? UpdatedAt { get; set; }
}