// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Analitica.Models;

public partial class ZhrWsMedidasData
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Begda { get; set; }

    public string? TipoData { get; set; }

    public string? Data { get; set; }

    public DateTime? UpdatedAt { get; set; }
}