// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsAtribOrgAtribOrg
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Unid { get; set; }

    public string? Abunid { get; set; }

    public string? DescUni { get; set; }

    public string? Situnid { get; set; }

    public string? DescSit { get; set; }

    public string? DtPosicao { get; set; }

    public string? Posicao { get; set; }

    public string? Sigla { get; set; }

    public string? DescPosi { get; set; }

    public string? Cargo { get; set; }

    public string? DescCarg { get; set; }

    public string? GrpEmpregad { get; set; }

    public string? DescEmp { get; set; }

    public string? Codsitcargo { get; set; }

    public string? DescSubemp { get; set; }

    public string? Dtsitquadro { get; set; }

    public string? Datapresenta { get; set; }

    public string? Stat1 { get; set; }

    public string? Stat1desc { get; set; }

    public string? Stat2 { get; set; }

    public string? Stat2desc { get; set; }

    public string? Descrelemprego { get; set; }

    public string? Begda { get; set; }

    public DateTime? UpdatedAt { get; set; }
}