// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Analitica.Models;

public partial class ZhrWsAtribOrgOm
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Ace { get; set; }

    public string? Acedesc { get; set; }

    public string? DetalheOrg { get; set; }

    public string? DetalhePos { get; set; }

    public DateTime? UpdatedAt { get; set; }
}