// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsAtribOrgDataMedidum
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Dar01 { get; set; }

    public string? Dat01 { get; set; }

    public string? DescMedida { get; set; }

    public DateTime? UpdatedAt { get; set; }
}