// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Analitica.Models;

public partial class ZhrWsContigentesContigente
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? TipoContig { get; set; }

    public string? Dias { get; set; }

    public string? Deducao { get; set; }

    public string? Dtinicio { get; set; }

    public string? Dtfim { get; set; }

    public string? DtinicioDed { get; set; }

    public string? DtfimDed { get; set; }

    public DateTime? UpdatedAt { get; set; }
}