// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsGetLicencas2001Licenca
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Licenca { get; set; }

    public string? LicencaDsc { get; set; }

    public string? Idregisto { get; set; }

    public string? Datainicio { get; set; }

    public string? Datafim { get; set; }

    public string? Horaini { get; set; }

    public string? Horafim { get; set; }

    public string? Horasausencia { get; set; }

    public string? Diasausencia { get; set; }

    public string? Diascalendario { get; set; }

    public string? Deducaocont { get; set; }

    public DateTime? UpdatedAt { get; set; }
}