// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Analitica.Models;

public partial class ZhrWsGetListViaturasPessoa
{
    public string? Ni { get; set; }

    public string? Numsap { get; set; }

    public string? Nome { get; set; }

    public string? NomeAbrev { get; set; }

    public string? Stat2 { get; set; }

    public string? GrupoEmpregado { get; set; }

    public string? Codsitcargo { get; set; }

    public string? Classe { get; set; }

    public string? ClasseDes { get; set; }

    public string? Unidade { get; set; }

    public string? Short { get; set; }

    public string? Codposto { get; set; }

    public string? Siglaposto { get; set; }

    public string? Siglaramo { get; set; }

    public string? Datafalecido { get; set; }

    public DateTime? MageCreatedAt { get; set; }

    public string? MageUpdatedAt { get; set; }
}