// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Analitica.Models;

public partial class ZhrWsRemunRemun
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Zzposr { get; set; }

    public string? Begda { get; set; }

    public string? Lgaxx { get; set; }

    public string? Betxx { get; set; }

    public string? Waers { get; set; }

    public string? Diferencial { get; set; }

    public DateTime? UpdatedAt { get; set; }
}