// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsGetIndicacoesTempTempoServico
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Datainicio { get; set; }

    public string? Datafim { get; set; }

    public string? Subty { get; set; }

    public string? Descsubtyp { get; set; }

    public string? Naoanalisar { get; set; }

    public string? Duryy { get; set; }

    public string? Dias { get; set; }

    public string? Text1 { get; set; }

    public string? Text2 { get; set; }

    public string? Text3 { get; set; }

    public string? Zttir { get; set; }

    public string? Zdescricao { get; set; }

    public string? Zzunid { get; set; }

    public string? Stext { get; set; }

    public string? Zprcat { get; set; }

    public string? Pcatt { get; set; }

    public string? Zthor { get; set; }

    public string? Znhor { get; set; }

    public string? Znmin { get; set; }

    public DateTime? UpdatedAt { get; set; }
}