// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Analitica.Models;

public partial class ZhrWsGetListViaturasViatura
{
    public string? Ni { get; set; }

    public string? Numsap { get; set; }

    public string? Begda { get; set; }

    public string? Endda { get; set; }

    public string? Marca { get; set; }

    public string? Matricula { get; set; }

    public string? Cartaoemitido { get; set; }

    public DateTime? MageCreatedAt { get; set; }

    public string? MageUpdatedAt { get; set; }
}