// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsAtribOrgHeader
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? DataIncorp { get; set; }

    public string? Datquadro { get; set; }

    public string? Datarma { get; set; }

    public string? Dataingresso { get; set; }

    public DateTime? UpdatedAt { get; set; }
}