// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Analitica.Models;

public partial class ZhrWsSigreDadosIdentificacao
{
    public string? Numsap { get; set; }

    public string? Grupo { get; set; }

    public string? Nip { get; set; }

    public string? Nim { get; set; }

    public string? Nii { get; set; }

    public string? Tipodoc { get; set; }

    public string? Numdocid { get; set; }

    public string? Dtemissao { get; set; }

    public string? Dtvalidade { get; set; }

    public string? Arquivo { get; set; }

    public DateTime? UpdatedAt { get; set; }
}