// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsHabilitacoesHabilitaco
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? CodGrauHab { get; set; }

    public string? Habilitacao { get; set; }

    public string? Grupformacao { get; set; }

    public string? Instituicao { get; set; }

    public string? Pais { get; set; }

    public string? Certificado { get; set; }

    public string? Notafinal { get; set; }

    public string? Dataconclusao { get; set; }

    public string? Curso { get; set; }

    public string? Descurso { get; set; }

    public string? Relevsammfa { get; set; }

    public DateTime? UpdatedAt { get; set; }
}