// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsFeriasFeria
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Ano { get; set; }

    public string? Contingente { get; set; }

    public string? DiasDisponiveis { get; set; }

    public string? DiasGozados { get; set; }

    public DateTime? UpdatedAt { get; set; }
}