// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Analitica.Models;

public partial class ZhrWsAtribOrgClassifProf
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Quadro { get; set; }

    public string? Codposto { get; set; }

    public string? Abposto { get; set; }

    public string? Desccatprof { get; set; }

    public string? Dtposto { get; set; }

    public string? Classe { get; set; }

    public string? DescClct { get; set; }

    public string? Armaserv { get; set; }

    public string? Descarma { get; set; }

    public string? Datarma { get; set; }

    public string? Especialidade { get; set; }

    public string? Descesp { get; set; }

    public string? DtEspecialidade { get; set; }

    public string? Quadespdesc { get; set; }

    public string? Zzgrad { get; set; }

    public string? DtZzgrad { get; set; }

    public string? Abpostograd { get; set; }

    public string? DescpostGrad { get; set; }

    public string? Numordposto { get; set; }

    public string? Agrupclassemar { get; set; }

    public string? Classemar { get; set; }

    public string? Datclassemar { get; set; }

    public string? Esp1 { get; set; }

    public string? Esp1Dsc { get; set; }

    public string? Esp2 { get; set; }

    public string? Esp2Dsc { get; set; }

    public string? Esp3 { get; set; }

    public string? Esp3Dsc { get; set; }

    public string? Codsubespec { get; set; }

    public string? Abrevespec { get; set; }

    public string? DtSubesp { get; set; }

    public string? Dataramoclasse { get; set; }

    public string? Descramoclasse { get; set; }

    public string? ZclasCod { get; set; }

    public string? ZramoCod { get; set; }

    public string? ZarmaCod { get; set; }

    public string? ZespfCod { get; set; }

    public string? ZqespCod { get; set; }

    public string? AreaFunc { get; set; }

    public string? AreaFuncDsc { get; set; }

    public string? EspOfSar { get; set; }

    public string? EspOfSarDsc { get; set; }

    public string? EspPra { get; set; }

    public string? EspPraDsc { get; set; }

    public string? Cargo { get; set; }

    public string? CargoDsc { get; set; }

    public string? Begda { get; set; }

    public DateTime? UpdatedAt { get; set; }
}