// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsSigreDadosPessoai
{
    public string? Numsap { get; set; }

    public string? Grupo { get; set; }

    public string? Nome { get; set; }

    public string? Apelido { get; set; }

    public string? Sexo { get; set; }

    public string? Dtnascimento { get; set; }

    public string? Paisnat { get; set; }

    public string? Distritonat { get; set; }

    public string? Concelhonat { get; set; }

    public string? Freguesianat { get; set; }

    public DateTime? UpdatedAt { get; set; }
}