// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsMobilidadesMobilidade
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Zzpref { get; set; }

    public string? ZzprefDesc { get; set; }

    public string? Zzunpref { get; set; }

    public string? ZzcodUnpref { get; set; }

    public string? ZzunprefDesc { get; set; }

    public string? Begda { get; set; }

    public string? Endda { get; set; }

    public string? Zzdate { get; set; }

    public string? Zzdat1 { get; set; }

    public string? Zzdatd { get; set; }

    public string? Subty { get; set; }

    public string? Zzdatr { get; set; }

    public string? ZzdespachoMobilidade { get; set; }

    public string? Zzdat2 { get; set; }

    public string? ZzentidadeMobilidade { get; set; }

    public string? ZzueosMobilidade { get; set; }

    public string? ZzueosMobilidadeDesc { get; set; }

    public string? ZzurgMobilidade { get; set; }

    public string? ZurgmDesc { get; set; }

    public string? Zzueos { get; set; }

    public string? ZzueosDesc { get; set; }

    public string? ZzplansMobilidade { get; set; }

    public string? ZzplansMobilidadeAbrv { get; set; }

    public string? ZzplansMobilidadeDesc { get; set; }

    public string? ZztipcMobilidade { get; set; }

    public string? ZzdtPrevistaMobilidade { get; set; }

    public string? ZzstatusMobilidade { get; set; }

    public string? Zzdescr { get; set; }

    public string? ZzdtStatusMobilidade { get; set; }

    public string? ZzobservacoesMobilidade { get; set; }

    public string? Zzsitu { get; set; }

    public string? ZzsituDesc { get; set; }

    public string? Zzorga { get; set; }

    public string? Zzfunc { get; set; }

    public string? ZfuncDesc { get; set; }

    public string? Zzidguiam { get; set; }

    public string? Zzunguiam { get; set; }

    public string? ZzunguiamDesc { get; set; }

    public string? Zzdatp { get; set; }

    public string? Zzhrprmr { get; set; }

    public string? Zzstat { get; set; }

    public string? ZstatDesc { get; set; }

    public string? Zztipn { get; set; }

    public string? ZtipnDesc { get; set; }

    public string? Zztipc { get; set; }

    public string? ZtipcDesc { get; set; }

    public string? Zztpcom { get; set; }

    public string? ZtipcomDesc { get; set; }

    public string? Zzurg { get; set; }

    public string? ZurgDesc { get; set; }

    public string? Zzcoloc { get; set; }

    public string? ZzprefDescr { get; set; }

    public string? Zzmiss { get; set; }

    public string? ZmissDesc { get; set; }

    public string? Zzundest { get; set; }

    public string? Zzabunid { get; set; }

    public string? ZzundestDesc { get; set; }

    public string? Zzunex { get; set; }

    public string? ZzunexDesc { get; set; }

    public string? Zzdati { get; set; }

    public string? Zhrmotexclu { get; set; }

    public string? Zhrmotexcludsc { get; set; }

    public string? Zhrobsmotexclu { get; set; }

    public DateTime? UpdatedAt { get; set; }
}