// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsPersonalDataOutrosDado
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? DataIni { get; set; }

    public string? DataFim { get; set; }

    public string? Subty { get; set; }

    public string? DescSub { get; set; }

    public string? ZzIndig { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string? Aus01 { get; set; }

    public string? Aus02 { get; set; }

    public string? Aus03 { get; set; }

    public string? Aus04 { get; set; }

    public string? Aus05 { get; set; }

    public string? Aus06 { get; set; }

    public string? Aus07 { get; set; }

    public string? Aus08 { get; set; }

    public string? Aus09 { get; set; }

    public string? Aus10 { get; set; }

    public string? Aus11 { get; set; }

    public string? Aus12 { get; set; }

    public string? Aus13 { get; set; }

    public string? Aus14 { get; set; }

    public string? Aus15 { get; set; }

    public string? Aus16 { get; set; }

    public string? Aus17 { get; set; }

    public string? Aus18 { get; set; }

    public string? Aus19 { get; set; }

    public string? Aus20 { get; set; }
}