// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsEndComEndereco
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Pais { get; set; }

    public string? Distrito { get; set; }

    public string? Descdist { get; set; }

    public string? Concelho { get; set; }

    public string? Desccon { get; set; }

    public string? Freguesia { get; set; }

    public string? Descfreg { get; set; }

    public string? Tiporesid { get; set; }

    public string? Stext { get; set; }

    public string? Rua { get; set; }

    public string? Rua2 { get; set; }

    public string? CodPostal { get; set; }

    public string? Telef { get; set; }

    public string? LocPostal { get; set; }

    public string? Tipocom1 { get; set; }

    public string? Numerocom1 { get; set; }

    public string? Tipocom2 { get; set; }

    public string? Numerocom2 { get; set; }

    public string? Tipocom3 { get; set; }

    public string? Numerocom3 { get; set; }

    public DateTime? UpdatedAt { get; set; }
}