// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsAumentosDiminuicoesAumento
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Espctempo { get; set; }

    public string? Denominacao { get; set; }

    public string? Data { get; set; }

    public string? Anos { get; set; }

    public string? Meses { get; set; }

    public string? Dias { get; set; }

    public string? Obs1 { get; set; }

    public string? Obs2 { get; set; }

    public string? Obs3 { get; set; }

    public DateTime? UpdatedAt { get; set; }
}