// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsRemunData
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? TipoData { get; set; }

    public string? Data { get; set; }

    public DateTime? UpdatedAt { get; set; }
}