// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Analitica.Models;

public partial class ZhrWsTemposServicosTempo
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Tipo { get; set; }

    public string? Anos { get; set; }

    public string? Meses { get; set; }

    public string? Dias { get; set; }

    public string? DataRef { get; set; }

    public string? Desctxt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}