// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsContratoContrato
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Cttyp { get; set; }

    public string? Eindt { get; set; }

    public string? Ctedt { get; set; }

    public string? Zzdlmc { get; set; }

    public string? Begda { get; set; }

    public string? Endda { get; set; }

    public string? Cttxt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}