// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Analitica.Models;

public partial class ZhrWsAtribOrgMonitPrazo
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Tipodatafim { get; set; }

    public string? Dataprev { get; set; }

    public DateTime? UpdatedAt { get; set; }
}