// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Pessoas.Integracao.Analitica.Models;

public partial class ZhrWsFuncoesFunco
{
    public string? Numsap { get; set; }

    public string? Ni { get; set; }

    public string? Subty { get; set; }

    public string? Objps { get; set; }

    public string? Sprps { get; set; }

    public string? Endda { get; set; }

    public string? Begda { get; set; }

    public string? Seqnr { get; set; }

    public string? Aedtm { get; set; }

    public string? Uname { get; set; }

    public string? Histo { get; set; }

    public string? Itxex { get; set; }

    public string? Refex { get; set; }

    public string? Ordex { get; set; }

    public string? Itbld { get; set; }

    public string? Preas { get; set; }

    public string? Flag1 { get; set; }

    public string? Flag2 { get; set; }

    public string? Flag3 { get; set; }

    public string? Flag4 { get; set; }

    public string? Rese1 { get; set; }

    public string? Rese2 { get; set; }

    public string? Grpvl { get; set; }

    public string? Zzordem { get; set; }

    public string? Zzcofun { get; set; }

    public string? Zzdesfun { get; set; }

    public string? Zzcoduni { get; set; }

    public string? Zzshortu { get; set; }

    public string? Zzdescun { get; set; }

    public string? Zzcodsub { get; set; }

    public string? Zzadsub { get; set; }

    public string? Zzdesub { get; set; }

    public string? Zzdocin { get; set; }

    public string? Zzdocfi { get; set; }

    public string? Zzobserv { get; set; }

    public string? Zzcondi { get; set; }

    public string? Zzfunac { get; set; }

    public string? Zzposup { get; set; }

    public string? Zzdocsu { get; set; }

    public string? Zzfuin { get; set; }

    public string? ZzsituMar { get; set; }

    public string? Zzdesit { get; set; }

    public string? Zzcofmi { get; set; }

    public string? Zzdefmi { get; set; }

    public DateTime? UpdatedAt { get; set; }
}