// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Analitica.Models;
using Microsoft.EntityFrameworkCore;

namespace Analitica.Infrastructure.Data;

public partial class AnaliticaDbContext : DbContext
{
    public AnaliticaDbContext(DbContextOptions<AnaliticaDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ZhrWsAptidaoAptidao> ZhrWsAptidaoAptidaos { get; set; }

    public virtual DbSet<ZhrWsAtribOrgAtribOrg> ZhrWsAtribOrgAtribOrgs { get; set; }

    public virtual DbSet<ZhrWsAtribOrgClassifProf> ZhrWsAtribOrgClassifProfs { get; set; }

    public virtual DbSet<ZhrWsAtribOrgDataMedidum> ZhrWsAtribOrgDataMedida { get; set; }

    public virtual DbSet<ZhrWsAtribOrgHeader> ZhrWsAtribOrgHeaders { get; set; }

    public virtual DbSet<ZhrWsAtribOrgInfoProm> ZhrWsAtribOrgInfoProms { get; set; }

    public virtual DbSet<ZhrWsAtribOrgMonitPrazo> ZhrWsAtribOrgMonitPrazos { get; set; }

    public virtual DbSet<ZhrWsAtribOrgOm> ZhrWsAtribOrgOms { get; set; }

    public virtual DbSet<ZhrWsAumentosDiminuicoesAumento> ZhrWsAumentosDiminuicoesAumentos { get; set; }

    public virtual DbSet<ZhrWsCondecorCondecoraco> ZhrWsCondecorCondecoracoes { get; set; }

    public virtual DbSet<ZhrWsContigentesContigente> ZhrWsContigentesContigentes { get; set; }

    public virtual DbSet<ZhrWsContratoContrato> ZhrWsContratoContratos { get; set; }

    public virtual DbSet<ZhrWsContratoSegSocial> ZhrWsContratoSegSocials { get; set; }

    public virtual DbSet<ZhrWsEndComComunicaco> ZhrWsEndComComunicacoes { get; set; }

    public virtual DbSet<ZhrWsEndComEndereco> ZhrWsEndComEnderecos { get; set; }

    public virtual DbSet<ZhrWsExamesMedExame> ZhrWsExamesMedExames { get; set; }

    public virtual DbSet<ZhrWsFeriasFeria> ZhrWsFeriasFerias { get; set; }

    public virtual DbSet<ZhrWsFormacaoFormacao> ZhrWsFormacaoFormacaos { get; set; }

    public virtual DbSet<ZhrWsFuncoesFunco> ZhrWsFuncoesFuncoes { get; set; }

    public virtual DbSet<ZhrWsGetIndicacoesTempTempoServico> ZhrWsGetIndicacoesTempTempoServicos { get; set; }

    public virtual DbSet<ZhrWsGetLicencas2001Licenca> ZhrWsGetLicencas2001Licencas { get; set; }

    public virtual DbSet<ZhrWsGetListViaturasPessoa> ZhrWsGetListViaturasPessoas { get; set; }

    public virtual DbSet<ZhrWsGetListViaturasViatura> ZhrWsGetListViaturasViaturas { get; set; }

    public virtual DbSet<ZhrWsGetListaUnidade> ZhrWsGetListaUnidades { get; set; }

    public virtual DbSet<ZhrWsGetLouvoresLouvor> ZhrWsGetLouvoresLouvors { get; set; }

    public virtual DbSet<ZhrWsGetProcAvegdiscProcesso> ZhrWsGetProcAvegdiscProcessos { get; set; }

    public virtual DbSet<ZhrWsHabilitacoesHabilitaco> ZhrWsHabilitacoesHabilitacoes { get; set; }

    public virtual DbSet<ZhrWsHorarioTabHorarioTrabalho> ZhrWsHorarioTabHorarioTrabalhos { get; set; }

    public virtual DbSet<ZhrWsIdentifBancario> ZhrWsIdentifBancarios { get; set; }

    public virtual DbSet<ZhrWsIdentifDadosFiscai> ZhrWsIdentifDadosFiscais { get; set; }

    public virtual DbSet<ZhrWsIdentifIdentificacao> ZhrWsIdentifIdentificacaos { get; set; }

    public virtual DbSet<ZhrWsMedidasData> ZhrWsMedidasDatas { get; set; }

    public virtual DbSet<ZhrWsMedidasMedida> ZhrWsMedidasMedidas { get; set; }

    public virtual DbSet<ZhrWsMobilidadesMobilidade> ZhrWsMobilidadesMobilidades { get; set; }

    public virtual DbSet<ZhrWsPersonalDataFamilium> ZhrWsPersonalDataFamilia { get; set; }

    public virtual DbSet<ZhrWsPersonalDataOutrosDado> ZhrWsPersonalDataOutrosDados { get; set; }

    public virtual DbSet<ZhrWsPersonalDataPessoai> ZhrWsPersonalDataPessoais { get; set; }

    public virtual DbSet<ZhrWsRemunData> ZhrWsRemunDatas { get; set; }

    public virtual DbSet<ZhrWsRemunHeader> ZhrWsRemunHeaders { get; set; }

    public virtual DbSet<ZhrWsRemunRemun> ZhrWsRemunRemuns { get; set; }

    public virtual DbSet<ZhrWsSigreDadosComunicaco> ZhrWsSigreDadosComunicacoes { get; set; }

    public virtual DbSet<ZhrWsSigreDadosEndereco> ZhrWsSigreDadosEnderecos { get; set; }

    public virtual DbSet<ZhrWsSigreDadosFamiliare> ZhrWsSigreDadosFamiliares { get; set; }

    public virtual DbSet<ZhrWsSigreDadosIdentificacao> ZhrWsSigreDadosIdentificacaos { get; set; }

    public virtual DbSet<ZhrWsSigreDadosPessoai> ZhrWsSigreDadosPessoais { get; set; }

    public virtual DbSet<ZhrWsTemposServicosTempo> ZhrWsTemposServicosTempos { get; set; }

    public virtual DbSet<ZhrWsgetPernr> ZhrWsgetPernrs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ZhrWsAptidaoAptidao>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsAptidao_Aptidao");

            entity.Property(e => e.AreaExame).IsUnicode(false);
            entity.Property(e => e.ArexamesDesc).IsUnicode(false);
            entity.Property(e => e.DataExame).IsUnicode(false);
            entity.Property(e => e.Denominacao).IsUnicode(false);
            entity.Property(e => e.ModalDesc).IsUnicode(false);
            entity.Property(e => e.Modalidade).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Observacoes).IsUnicode(false);
            entity.Property(e => e.Resultado).IsUnicode(false);
            entity.Property(e => e.ResultadoDesc).IsUnicode(false);
            entity.Property(e => e.ServicoMedInt).IsUnicode(false);
            entity.Property(e => e.Subty).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Valor).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsAtribOrgAtribOrg>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsAtribOrg_AtribOrg");

            entity.Property(e => e.Abunid).IsUnicode(false);
            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.Cargo).IsUnicode(false);
            entity.Property(e => e.Codsitcargo).IsUnicode(false);
            entity.Property(e => e.Datapresenta).IsUnicode(false);
            entity.Property(e => e.DescCarg).IsUnicode(false);
            entity.Property(e => e.DescEmp).IsUnicode(false);
            entity.Property(e => e.DescPosi).IsUnicode(false);
            entity.Property(e => e.DescSit).IsUnicode(false);
            entity.Property(e => e.DescSubemp).IsUnicode(false);
            entity.Property(e => e.DescUni).IsUnicode(false);
            entity.Property(e => e.Descrelemprego).IsUnicode(false);
            entity.Property(e => e.DtPosicao).IsUnicode(false);
            entity.Property(e => e.Dtsitquadro).IsUnicode(false);
            entity.Property(e => e.GrpEmpregad).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Posicao).IsUnicode(false);
            entity.Property(e => e.Sigla).IsUnicode(false);
            entity.Property(e => e.Situnid).IsUnicode(false);
            entity.Property(e => e.Stat1).IsUnicode(false);
            entity.Property(e => e.Stat1desc).IsUnicode(false);
            entity.Property(e => e.Stat2).IsUnicode(false);
            entity.Property(e => e.Stat2desc).IsUnicode(false);
            entity.Property(e => e.Unid).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsAtribOrgClassifProf>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsAtribOrg_ClassifProf");

            entity.Property(e => e.Abposto).IsUnicode(false);
            entity.Property(e => e.Abpostograd).IsUnicode(false);
            entity.Property(e => e.Abrevespec).IsUnicode(false);
            entity.Property(e => e.Agrupclassemar).IsUnicode(false);
            entity.Property(e => e.AreaFunc).IsUnicode(false);
            entity.Property(e => e.AreaFuncDsc).IsUnicode(false);
            entity.Property(e => e.Armaserv).IsUnicode(false);
            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.Cargo).IsUnicode(false);
            entity.Property(e => e.CargoDsc).IsUnicode(false);
            entity.Property(e => e.Classe).IsUnicode(false);
            entity.Property(e => e.Classemar).IsUnicode(false);
            entity.Property(e => e.Codposto).IsUnicode(false);
            entity.Property(e => e.Codsubespec).IsUnicode(false);
            entity.Property(e => e.Dataramoclasse).IsUnicode(false);
            entity.Property(e => e.Datarma).IsUnicode(false);
            entity.Property(e => e.Datclassemar).IsUnicode(false);
            entity.Property(e => e.DescClct).IsUnicode(false);
            entity.Property(e => e.Descarma).IsUnicode(false);
            entity.Property(e => e.Desccatprof).IsUnicode(false);
            entity.Property(e => e.Descesp).IsUnicode(false);
            entity.Property(e => e.DescpostGrad).IsUnicode(false);
            entity.Property(e => e.Descramoclasse).IsUnicode(false);
            entity.Property(e => e.DtEspecialidade).IsUnicode(false);
            entity.Property(e => e.DtSubesp).IsUnicode(false);
            entity.Property(e => e.DtZzgrad).IsUnicode(false);
            entity.Property(e => e.Dtposto).IsUnicode(false);
            entity.Property(e => e.Esp1).IsUnicode(false);
            entity.Property(e => e.Esp1Dsc).IsUnicode(false);
            entity.Property(e => e.Esp2).IsUnicode(false);
            entity.Property(e => e.Esp2Dsc).IsUnicode(false);
            entity.Property(e => e.Esp3).IsUnicode(false);
            entity.Property(e => e.Esp3Dsc).IsUnicode(false);
            entity.Property(e => e.EspOfSar).IsUnicode(false);
            entity.Property(e => e.EspOfSarDsc).IsUnicode(false);
            entity.Property(e => e.EspPra).IsUnicode(false);
            entity.Property(e => e.EspPraDsc).IsUnicode(false);
            entity.Property(e => e.Especialidade).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numordposto).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Quadespdesc).IsUnicode(false);
            entity.Property(e => e.Quadro).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.ZarmaCod).IsUnicode(false);
            entity.Property(e => e.ZclasCod).IsUnicode(false);
            entity.Property(e => e.ZespfCod).IsUnicode(false);
            entity.Property(e => e.ZqespCod).IsUnicode(false);
            entity.Property(e => e.ZramoCod).IsUnicode(false);
            entity.Property(e => e.Zzgrad).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsAtribOrgDataMedidum>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsAtribOrg_DataMedida");

            entity.Property(e => e.Dar01).IsUnicode(false);
            entity.Property(e => e.Dat01).IsUnicode(false);
            entity.Property(e => e.DescMedida).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsAtribOrgHeader>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsAtribOrg_Header");

            entity.Property(e => e.DataIncorp).IsUnicode(false);
            entity.Property(e => e.Dataingresso).IsUnicode(false);
            entity.Property(e => e.Datarma).IsUnicode(false);
            entity.Property(e => e.Datquadro).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsAtribOrgInfoProm>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsAtribOrg_InfoProm");

            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.ClasseMilitar).IsUnicode(false);
            entity.Property(e => e.Endda).IsUnicode(false);
            entity.Property(e => e.Motdemora).IsUnicode(false);
            entity.Property(e => e.Motpret).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Posto).IsUnicode(false);
            entity.Property(e => e.Sitprom).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Zarfu).IsUnicode(false);
            entity.Property(e => e.Zarma).IsUnicode(false);
            entity.Property(e => e.Zcarg).IsUnicode(false);
            entity.Property(e => e.Zdatapromo).IsUnicode(false);
            entity.Property(e => e.ZdemDes).IsUnicode(false);
            entity.Property(e => e.ZespxOs).IsUnicode(false);
            entity.Property(e => e.ZespxP).IsUnicode(false);
            entity.Property(e => e.Zordem).IsUnicode(false);
            entity.Property(e => e.ZpretDes).IsUnicode(false);
            entity.Property(e => e.Zzdata).IsUnicode(false);
            entity.Property(e => e.Zzdesp).IsUnicode(false);
            entity.Property(e => e.Zzdispal).IsUnicode(false);
            entity.Property(e => e.Zznumpubl).IsUnicode(false);
            entity.Property(e => e.Zzpubl).IsUnicode(false);
            entity.Property(e => e.Zzseri).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsAtribOrgMonitPrazo>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsAtribOrg_MonitPrazos");

            entity.Property(e => e.Dataprev).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Tipodatafim).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsAtribOrgOm>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsAtribOrg_Om");

            entity.Property(e => e.Ace).IsUnicode(false);
            entity.Property(e => e.Acedesc).IsUnicode(false);
            entity.Property(e => e.DetalheOrg).IsUnicode(false);
            entity.Property(e => e.DetalhePos).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsAumentosDiminuicoesAumento>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsAumentosDiminuicoes_Aumentos");

            entity.Property(e => e.Anos).IsUnicode(false);
            entity.Property(e => e.Data).IsUnicode(false);
            entity.Property(e => e.Denominacao).IsUnicode(false);
            entity.Property(e => e.Dias).IsUnicode(false);
            entity.Property(e => e.Espctempo).IsUnicode(false);
            entity.Property(e => e.Meses).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Obs1).IsUnicode(false);
            entity.Property(e => e.Obs2).IsUnicode(false);
            entity.Property(e => e.Obs3).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsCondecorCondecoraco>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsCondecor_Condecoracoes");

            entity.Property(e => e.CodUnid).IsUnicode(false);
            entity.Property(e => e.Cond).IsUnicode(false);
            entity.Property(e => e.Datadespacho).IsUnicode(false);
            entity.Property(e => e.Datainicio).IsUnicode(false);
            entity.Property(e => e.Dataperdireito).IsUnicode(false);
            entity.Property(e => e.Datarequerimento).IsUnicode(false);
            entity.Property(e => e.Datcondecor).IsUnicode(false);
            entity.Property(e => e.Datpublicacao).IsUnicode(false);
            entity.Property(e => e.DescUnid).IsUnicode(false);
            entity.Property(e => e.DescUnidH).IsUnicode(false);
            entity.Property(e => e.Descondecor).IsUnicode(false);
            entity.Property(e => e.Legenda).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Ordcondecor).IsUnicode(false);
            entity.Property(e => e.PostoCat).IsUnicode(false);
            entity.Property(e => e.Tpcond).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsContigentesContigente>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsContigentes_Contigentes");

            entity.Property(e => e.Deducao).IsUnicode(false);
            entity.Property(e => e.Dias).IsUnicode(false);
            entity.Property(e => e.Dtfim).IsUnicode(false);
            entity.Property(e => e.DtfimDed).IsUnicode(false);
            entity.Property(e => e.Dtinicio).IsUnicode(false);
            entity.Property(e => e.DtinicioDed).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.TipoContig).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsContratoContrato>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsContrato_Contrato");

            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.Ctedt).IsUnicode(false);
            entity.Property(e => e.Cttxt).IsUnicode(false);
            entity.Property(e => e.Cttyp).IsUnicode(false);
            entity.Property(e => e.Eindt).IsUnicode(false);
            entity.Property(e => e.Endda).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Zzdlmc).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsContratoSegSocial>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsContrato_SegSocial");

            entity.Property(e => e.Adsee).IsUnicode(false);
            entity.Property(e => e.Adsefac).IsUnicode(false);
            entity.Property(e => e.Adsenum).IsUnicode(false);
            entity.Property(e => e.Adsfadt).IsUnicode(false);
            entity.Property(e => e.Cgacod).IsUnicode(false);
            entity.Property(e => e.Cganum).IsUnicode(false);
            entity.Property(e => e.Cttxt).IsUnicode(false);
            entity.Property(e => e.Descadse).IsUnicode(false);
            entity.Property(e => e.Descregimess).IsUnicode(false);
            entity.Property(e => e.Desctext).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Rgcod).IsUnicode(false);
            entity.Property(e => e.Ssdte).IsUnicode(false);
            entity.Property(e => e.Ssnum).IsUnicode(false);
            entity.Property(e => e.Ssrgm).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsEndComComunicaco>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsEndCom_Comunicacoes");

            entity.Property(e => e.IdComunic).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Subtipcom).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsEndComEndereco>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsEndCom_Endereco");

            entity.Property(e => e.CodPostal).IsUnicode(false);
            entity.Property(e => e.Concelho).IsUnicode(false);
            entity.Property(e => e.Desccon).IsUnicode(false);
            entity.Property(e => e.Descdist).IsUnicode(false);
            entity.Property(e => e.Descfreg).IsUnicode(false);
            entity.Property(e => e.Distrito).IsUnicode(false);
            entity.Property(e => e.Freguesia).IsUnicode(false);
            entity.Property(e => e.LocPostal).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numerocom1).IsUnicode(false);
            entity.Property(e => e.Numerocom2).IsUnicode(false);
            entity.Property(e => e.Numerocom3).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Pais).IsUnicode(false);
            entity.Property(e => e.Rua).IsUnicode(false);
            entity.Property(e => e.Rua2).IsUnicode(false);
            entity.Property(e => e.Stext).IsUnicode(false);
            entity.Property(e => e.Telef).IsUnicode(false);
            entity.Property(e => e.Tipocom1).IsUnicode(false);
            entity.Property(e => e.Tipocom2).IsUnicode(false);
            entity.Property(e => e.Tipocom3).IsUnicode(false);
            entity.Property(e => e.Tiporesid).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsExamesMedExame>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsExamesMed_Exames");

            entity.Property(e => e.AreaExame).IsUnicode(false);
            entity.Property(e => e.ArexamesDesc).IsUnicode(false);
            entity.Property(e => e.DataExame).IsUnicode(false);
            entity.Property(e => e.ModalDesc).IsUnicode(false);
            entity.Property(e => e.Modalidade).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.ServicoMedInt).IsUnicode(false);
            entity.Property(e => e.Subty).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Valor).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsFeriasFeria>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsFerias_Ferias");

            entity.Property(e => e.Ano).IsUnicode(false);
            entity.Property(e => e.Contingente).IsUnicode(false);
            entity.Property(e => e.DiasDisponiveis).IsUnicode(false);
            entity.Property(e => e.DiasGozados).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsFormacaoFormacao>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsFormacao_Formacao");

            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.Endda).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Zzauto).IsUnicode(false);
            entity.Property(e => e.ZzcurIngress).IsUnicode(false);
            entity.Property(e => e.Zzdate).IsUnicode(false);
            entity.Property(e => e.Zzdays).IsUnicode(false);
            entity.Property(e => e.ZzdocPublic).IsUnicode(false);
            entity.Property(e => e.Zzemark).IsUnicode(false);
            entity.Property(e => e.Zzespe).IsUnicode(false);
            entity.Property(e => e.Zzfimcurso).IsUnicode(false);
            entity.Property(e => e.Zzhours).IsUnicode(false);
            entity.Property(e => e.Zziext).IsUnicode(false);
            entity.Property(e => e.Zzikost).IsUnicode(false);
            entity.Property(e => e.Zzinicurso).IsUnicode(false);
            entity.Property(e => e.Zziwaer).IsUnicode(false);
            entity.Property(e => e.Zznump).IsUnicode(false);
            entity.Property(e => e.Zzobjid).IsUnicode(false);
            entity.Property(e => e.Zzpubl).IsUnicode(false);
            entity.Property(e => e.Zzquantifica).IsUnicode(false);
            entity.Property(e => e.ZzrelevAntig).IsUnicode(false);
            entity.Property(e => e.Zzserie).IsUnicode(false);
            entity.Property(e => e.Zzshort).IsUnicode(false);
            entity.Property(e => e.Zzsiammfa).IsUnicode(false);
            entity.Property(e => e.Zzslart).IsUnicode(false);
            entity.Property(e => e.Zzstext).IsUnicode(false);
            entity.Property(e => e.ZzstextL).IsUnicode(false);
            entity.Property(e => e.ZztipoCurso).IsUnicode(false);
            entity.Property(e => e.ZztipoCursoDesc).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsFuncoesFunco>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsFuncoes_Funcoes");

            entity.Property(e => e.Aedtm).IsUnicode(false);
            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.Endda).IsUnicode(false);
            entity.Property(e => e.Flag1).IsUnicode(false);
            entity.Property(e => e.Flag2).IsUnicode(false);
            entity.Property(e => e.Flag3).IsUnicode(false);
            entity.Property(e => e.Flag4).IsUnicode(false);
            entity.Property(e => e.Grpvl).IsUnicode(false);
            entity.Property(e => e.Histo).IsUnicode(false);
            entity.Property(e => e.Itbld).IsUnicode(false);
            entity.Property(e => e.Itxex).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Objps).IsUnicode(false);
            entity.Property(e => e.Ordex).IsUnicode(false);
            entity.Property(e => e.Preas).IsUnicode(false);
            entity.Property(e => e.Refex).IsUnicode(false);
            entity.Property(e => e.Rese1).IsUnicode(false);
            entity.Property(e => e.Rese2).IsUnicode(false);
            entity.Property(e => e.Seqnr).IsUnicode(false);
            entity.Property(e => e.Sprps).IsUnicode(false);
            entity.Property(e => e.Subty).IsUnicode(false);
            entity.Property(e => e.Uname).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Zzadsub).IsUnicode(false);
            entity.Property(e => e.Zzcodsub).IsUnicode(false);
            entity.Property(e => e.Zzcoduni).IsUnicode(false);
            entity.Property(e => e.Zzcofmi).IsUnicode(false);
            entity.Property(e => e.Zzcofun).IsUnicode(false);
            entity.Property(e => e.Zzcondi).IsUnicode(false);
            entity.Property(e => e.Zzdefmi).IsUnicode(false);
            entity.Property(e => e.Zzdescun).IsUnicode(false);
            entity.Property(e => e.Zzdesfun).IsUnicode(false);
            entity.Property(e => e.Zzdesit).IsUnicode(false);
            entity.Property(e => e.Zzdesub).IsUnicode(false);
            entity.Property(e => e.Zzdocfi).IsUnicode(false);
            entity.Property(e => e.Zzdocin).IsUnicode(false);
            entity.Property(e => e.Zzdocsu).IsUnicode(false);
            entity.Property(e => e.Zzfuin).IsUnicode(false);
            entity.Property(e => e.Zzfunac).IsUnicode(false);
            entity.Property(e => e.Zzobserv).IsUnicode(false);
            entity.Property(e => e.Zzordem).IsUnicode(false);
            entity.Property(e => e.Zzposup).IsUnicode(false);
            entity.Property(e => e.Zzshortu).IsUnicode(false);
            entity.Property(e => e.ZzsituMar).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsGetIndicacoesTempTempoServico>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsGetIndicacoesTemp_TempoServico");

            entity.Property(e => e.Datafim).IsUnicode(false);
            entity.Property(e => e.Datainicio).IsUnicode(false);
            entity.Property(e => e.Descsubtyp).IsUnicode(false);
            entity.Property(e => e.Dias).IsUnicode(false);
            entity.Property(e => e.Duryy).IsUnicode(false);
            entity.Property(e => e.Naoanalisar).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Pcatt).IsUnicode(false);
            entity.Property(e => e.Stext).IsUnicode(false);
            entity.Property(e => e.Subty).IsUnicode(false);
            entity.Property(e => e.Text1).IsUnicode(false);
            entity.Property(e => e.Text2).IsUnicode(false);
            entity.Property(e => e.Text3).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Zdescricao).IsUnicode(false);
            entity.Property(e => e.Znhor).IsUnicode(false);
            entity.Property(e => e.Znmin).IsUnicode(false);
            entity.Property(e => e.Zprcat).IsUnicode(false);
            entity.Property(e => e.Zthor).IsUnicode(false);
            entity.Property(e => e.Zttir).IsUnicode(false);
            entity.Property(e => e.Zzunid).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsGetLicencas2001Licenca>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsGetLicencas2001_Licencas");

            entity.Property(e => e.Datafim).IsUnicode(false);
            entity.Property(e => e.Datainicio).IsUnicode(false);
            entity.Property(e => e.Deducaocont).IsUnicode(false);
            entity.Property(e => e.Diasausencia).IsUnicode(false);
            entity.Property(e => e.Diascalendario).IsUnicode(false);
            entity.Property(e => e.Horafim).IsUnicode(false);
            entity.Property(e => e.Horaini).IsUnicode(false);
            entity.Property(e => e.Horasausencia).IsUnicode(false);
            entity.Property(e => e.Idregisto).IsUnicode(false);
            entity.Property(e => e.Licenca).IsUnicode(false);
            entity.Property(e => e.LicencaDsc).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsGetListViaturasPessoa>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsGetListViaturas_Pessoas");

            entity.Property(e => e.Classe).HasMaxLength(10);
            entity.Property(e => e.ClasseDes).HasMaxLength(100);
            entity.Property(e => e.Codposto).HasMaxLength(20);
            entity.Property(e => e.Codsitcargo).HasMaxLength(10);
            entity.Property(e => e.Datafalecido).HasMaxLength(10);
            entity.Property(e => e.GrupoEmpregado).HasMaxLength(10);
            entity.Property(e => e.MageCreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("_mage_created_at");
            entity.Property(e => e.MageUpdatedAt)
                .HasMaxLength(52)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("_mage_updated_at");
            entity.Property(e => e.Ni).HasMaxLength(15);
            entity.Property(e => e.Nome).HasMaxLength(255);
            entity.Property(e => e.NomeAbrev).HasMaxLength(100);
            entity.Property(e => e.Numsap).HasMaxLength(15);
            entity.Property(e => e.Short).HasMaxLength(25);
            entity.Property(e => e.Siglaposto).HasMaxLength(20);
            entity.Property(e => e.Siglaramo).HasMaxLength(20);
            entity.Property(e => e.Stat2).HasMaxLength(10);
            entity.Property(e => e.Unidade).HasMaxLength(20);
        });

        modelBuilder.Entity<ZhrWsGetListViaturasViatura>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsGetListViaturas_Viatura");

            entity.Property(e => e.Begda).HasMaxLength(10);
            entity.Property(e => e.Cartaoemitido).HasMaxLength(1);
            entity.Property(e => e.Endda).HasMaxLength(10);
            entity.Property(e => e.MageCreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("_mage_created_at");
            entity.Property(e => e.MageUpdatedAt)
                .HasMaxLength(52)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("_mage_updated_at");
            entity.Property(e => e.Marca).HasMaxLength(50);
            entity.Property(e => e.Matricula).HasMaxLength(20);
            entity.Property(e => e.Ni).HasMaxLength(15);
            entity.Property(e => e.Numsap).HasMaxLength(15);
        });

        modelBuilder.Entity<ZhrWsGetListaUnidade>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsGetListaUnidade");

            entity.Property(e => e.Classe).HasMaxLength(50);
            entity.Property(e => e.ClasseDsc).HasMaxLength(50);
            entity.Property(e => e.Datapresenta).HasMaxLength(50);
            entity.Property(e => e.Ni).HasMaxLength(10);
            entity.Property(e => e.NomeAbreviado).HasMaxLength(50);
            entity.Property(e => e.Nomecompleto).HasMaxLength(500);
            entity.Property(e => e.Numsap).HasMaxLength(50);
            entity.Property(e => e.Posto).HasMaxLength(50);
            entity.Property(e => e.Quadro).HasMaxLength(50);
            entity.Property(e => e.QuadroDsc).HasMaxLength(50);
            entity.Property(e => e.Unidade).HasMaxLength(50);
            entity.Property(e => e.UnidadeDsc).HasMaxLength(500);
        });

        modelBuilder.Entity<ZhrWsGetLouvoresLouvor>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsGetLouvores_Louvor");

            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.Cativacao).IsUnicode(false);
            entity.Property(e => e.CodUnid).IsUnicode(false);
            entity.Property(e => e.Comandforun).IsUnicode(false);
            entity.Property(e => e.Componop).IsUnicode(false);
            entity.Property(e => e.Dataavocacao).IsUnicode(false);
            entity.Property(e => e.Datacativa).IsUnicode(false);
            entity.Property(e => e.Datahomologa).IsUnicode(false);
            entity.Property(e => e.Datalouv).IsUnicode(false);
            entity.Property(e => e.Datapublicacao).IsUnicode(false);
            entity.Property(e => e.DescCond).IsUnicode(false);
            entity.Property(e => e.DescUnid).IsUnicode(false);
            entity.Property(e => e.DescUnidH).IsUnicode(false);
            entity.Property(e => e.Descpubl).IsUnicode(false);
            entity.Property(e => e.Docpubliclouvor).IsUnicode(false);
            entity.Property(e => e.Emcampan).IsUnicode(false);
            entity.Property(e => e.Emendfnd).IsUnicode(false);
            entity.Property(e => e.Endda).IsUnicode(false);
            entity.Property(e => e.Entid).IsUnicode(false);
            entity.Property(e => e.Feitcombat).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Nivellouvor).IsUnicode(false);
            entity.Property(e => e.Numpublicacao).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Ordlouv).IsUnicode(false);
            entity.Property(e => e.Postentavoc).IsUnicode(false);
            entity.Property(e => e.PostoCat).IsUnicode(false);
            entity.Property(e => e.Relsiammfa).IsUnicode(false);
            entity.Property(e => e.Seriepublicacao).IsUnicode(false);
            entity.Property(e => e.Tiplouv).IsUnicode(false);
            entity.Property(e => e.Unidade).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsGetProcAvegdiscProcesso>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsGetProcAvegdisc_Processos");

            entity.Property(e => e.Anulacaopena).IsUnicode(false);
            entity.Property(e => e.Anulsansaoapl).IsUnicode(false);
            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.CulpabilidadeArguido).IsUnicode(false);
            entity.Property(e => e.Dataanulacaopena).IsUnicode(false);
            entity.Property(e => e.Databertproc).IsUnicode(false);
            entity.Property(e => e.Datadocumento).IsUnicode(false);
            entity.Property(e => e.Dataencproc).IsUnicode(false);
            entity.Property(e => e.Dataencprocedi).IsUnicode(false);
            entity.Property(e => e.Dataencprocesso).IsUnicode(false);
            entity.Property(e => e.Dataestado).IsUnicode(false);
            entity.Property(e => e.Dataextincao).IsUnicode(false);
            entity.Property(e => e.Datahomolocacao).IsUnicode(false);
            entity.Property(e => e.Datainicmppn).IsUnicode(false);
            entity.Property(e => e.Datanotif).IsUnicode(false);
            entity.Property(e => e.Datanotifrec).IsUnicode(false);
            entity.Property(e => e.Datatransjulg).IsUnicode(false);
            entity.Property(e => e.Datdespacho).IsUnicode(false);
            entity.Property(e => e.DefReqrev).IsUnicode(false);
            entity.Property(e => e.Docpublica).IsUnicode(false);
            entity.Property(e => e.Endda).IsUnicode(false);
            entity.Property(e => e.Entidadedecide).IsUnicode(false);
            entity.Property(e => e.Estado).IsUnicode(false);
            entity.Property(e => e.Gradacaopena).IsUnicode(false);
            entity.Property(e => e.Loclarq).IsUnicode(false);
            entity.Property(e => e.Motivoextincao).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Nprocesso).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Observacoes).IsUnicode(false);
            entity.Property(e => e.Observacoes1).IsUnicode(false);
            entity.Property(e => e.Postofuncao).IsUnicode(false);
            entity.Property(e => e.Tipopena).IsUnicode(false);
            entity.Property(e => e.Tipoproc).IsUnicode(false);
            entity.Property(e => e.TipoprocDsc).IsUnicode(false);
            entity.Property(e => e.Unidacontagem).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsHabilitacoesHabilitaco>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsHabilitacoes_Habilitacoes");

            entity.Property(e => e.Certificado).IsUnicode(false);
            entity.Property(e => e.CodGrauHab).IsUnicode(false);
            entity.Property(e => e.Curso).IsUnicode(false);
            entity.Property(e => e.Dataconclusao).IsUnicode(false);
            entity.Property(e => e.Descurso).IsUnicode(false);
            entity.Property(e => e.Grupformacao).IsUnicode(false);
            entity.Property(e => e.Habilitacao).IsUnicode(false);
            entity.Property(e => e.Instituicao).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Notafinal).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Pais).IsUnicode(false);
            entity.Property(e => e.Relevsammfa).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsHorarioTabHorarioTrabalho>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsHorarioTab_HorarioTrabalho");

            entity.Property(e => e.AbrModHorario).IsUnicode(false);
            entity.Property(e => e.CodModHorario).IsUnicode(false);
            entity.Property(e => e.DatIniHorario).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.PerDdHorario).IsUnicode(false);
            entity.Property(e => e.PerSemHorario).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsIdentifBancario>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsIdentif_Bancarios");

            entity.Property(e => e.ChaveBanco).IsUnicode(false);
            entity.Property(e => e.ChaveControl).IsUnicode(false);
            entity.Property(e => e.CodBanco).IsUnicode(false);
            entity.Property(e => e.DigControl).IsUnicode(false);
            entity.Property(e => e.Iban).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.NumConta).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsIdentifDadosFiscai>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsIdentif_DadosFiscais");

            entity.Property(e => e.CodRepFin).IsUnicode(false);
            entity.Property(e => e.DescatgRend).IsUnicode(false);
            entity.Property(e => e.DescestadoCivil).IsUnicode(false);
            entity.Property(e => e.DescodRepFin).IsUnicode(false);
            entity.Property(e => e.Hspse).IsUnicode(false);
            entity.Property(e => e.IndResid).IsUnicode(false);
            entity.Property(e => e.Mstat).IsUnicode(false);
            entity.Property(e => e.Ndeph).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Nif).IsUnicode(false);
            entity.Property(e => e.Nrdep).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Resid).IsUnicode(false);
            entity.Property(e => e.Svrat).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Wspse).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsIdentifIdentificacao>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsIdentif_Identificacao");

            entity.Property(e => e.Autemiss).IsUnicode(false);
            entity.Property(e => e.Dtemissao).IsUnicode(false);
            entity.Property(e => e.Dtvalidade).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numdocid).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Paisemiss).IsUnicode(false);
            entity.Property(e => e.Tipodoc).IsUnicode(false);
            entity.Property(e => e.Tipodocdesc).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.ZzdispId).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsMedidasData>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsMedidas_Datas");

            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.Data).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.TipoData).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsMedidasMedida>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsMedidas_Medidas");

            entity.Property(e => e.Dtgrad).IsUnicode(false);
            entity.Property(e => e.Medida).IsUnicode(false);
            entity.Property(e => e.Motivo).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Stat1).IsUnicode(false);
            entity.Property(e => e.Stat2).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsMobilidadesMobilidade>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsMobilidades_Mobilidades");

            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.Endda).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Subty).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.ZfuncDesc).IsUnicode(false);
            entity.Property(e => e.Zhrmotexclu).IsUnicode(false);
            entity.Property(e => e.Zhrmotexcludsc).IsUnicode(false);
            entity.Property(e => e.Zhrobsmotexclu).IsUnicode(false);
            entity.Property(e => e.ZmissDesc).IsUnicode(false);
            entity.Property(e => e.ZstatDesc).IsUnicode(false);
            entity.Property(e => e.ZtipcDesc).IsUnicode(false);
            entity.Property(e => e.ZtipcomDesc).IsUnicode(false);
            entity.Property(e => e.ZtipnDesc).IsUnicode(false);
            entity.Property(e => e.ZurgDesc).IsUnicode(false);
            entity.Property(e => e.ZurgmDesc).IsUnicode(false);
            entity.Property(e => e.Zzabunid).IsUnicode(false);
            entity.Property(e => e.ZzcodUnpref).IsUnicode(false);
            entity.Property(e => e.Zzcoloc).IsUnicode(false);
            entity.Property(e => e.Zzdat1).IsUnicode(false);
            entity.Property(e => e.Zzdat2).IsUnicode(false);
            entity.Property(e => e.Zzdatd).IsUnicode(false);
            entity.Property(e => e.Zzdate).IsUnicode(false);
            entity.Property(e => e.Zzdati).IsUnicode(false);
            entity.Property(e => e.Zzdatp).IsUnicode(false);
            entity.Property(e => e.Zzdatr).IsUnicode(false);
            entity.Property(e => e.Zzdescr).IsUnicode(false);
            entity.Property(e => e.ZzdespachoMobilidade).IsUnicode(false);
            entity.Property(e => e.ZzdtPrevistaMobilidade).IsUnicode(false);
            entity.Property(e => e.ZzdtStatusMobilidade).IsUnicode(false);
            entity.Property(e => e.ZzentidadeMobilidade).IsUnicode(false);
            entity.Property(e => e.Zzfunc).IsUnicode(false);
            entity.Property(e => e.Zzhrprmr).IsUnicode(false);
            entity.Property(e => e.Zzidguiam).IsUnicode(false);
            entity.Property(e => e.Zzmiss).IsUnicode(false);
            entity.Property(e => e.ZzobservacoesMobilidade).IsUnicode(false);
            entity.Property(e => e.Zzorga).IsUnicode(false);
            entity.Property(e => e.ZzplansMobilidade).IsUnicode(false);
            entity.Property(e => e.ZzplansMobilidadeAbrv).IsUnicode(false);
            entity.Property(e => e.ZzplansMobilidadeDesc).IsUnicode(false);
            entity.Property(e => e.Zzpref).IsUnicode(false);
            entity.Property(e => e.ZzprefDesc).IsUnicode(false);
            entity.Property(e => e.ZzprefDescr).IsUnicode(false);
            entity.Property(e => e.Zzsitu).IsUnicode(false);
            entity.Property(e => e.ZzsituDesc).IsUnicode(false);
            entity.Property(e => e.Zzstat).IsUnicode(false);
            entity.Property(e => e.ZzstatusMobilidade).IsUnicode(false);
            entity.Property(e => e.Zztipc).IsUnicode(false);
            entity.Property(e => e.ZztipcMobilidade).IsUnicode(false);
            entity.Property(e => e.Zztipn).IsUnicode(false);
            entity.Property(e => e.Zztpcom).IsUnicode(false);
            entity.Property(e => e.Zzueos).IsUnicode(false);
            entity.Property(e => e.ZzueosDesc).IsUnicode(false);
            entity.Property(e => e.ZzueosMobilidade).IsUnicode(false);
            entity.Property(e => e.ZzueosMobilidadeDesc).IsUnicode(false);
            entity.Property(e => e.Zzundest).IsUnicode(false);
            entity.Property(e => e.ZzundestDesc).IsUnicode(false);
            entity.Property(e => e.Zzunex).IsUnicode(false);
            entity.Property(e => e.ZzunexDesc).IsUnicode(false);
            entity.Property(e => e.Zzunguiam).IsUnicode(false);
            entity.Property(e => e.ZzunguiamDesc).IsUnicode(false);
            entity.Property(e => e.Zzunpref).IsUnicode(false);
            entity.Property(e => e.ZzunprefDesc).IsUnicode(false);
            entity.Property(e => e.Zzurg).IsUnicode(false);
            entity.Property(e => e.ZzurgMobilidade).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsPersonalDataFamilium>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsPersonalData_Familia");

            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.Benef).IsUnicode(false);
            entity.Property(e => e.Dtfalec).IsUnicode(false);
            entity.Property(e => e.Endda).IsUnicode(false);
            entity.Property(e => e.Famsa).IsUnicode(false);
            entity.Property(e => e.Fanam).IsUnicode(false);
            entity.Property(e => e.Fanat).IsUnicode(false);
            entity.Property(e => e.Fasex).IsUnicode(false);
            entity.Property(e => e.Fcnam).IsUnicode(false);
            entity.Property(e => e.Fgbdt).IsUnicode(false);
            entity.Property(e => e.Finum).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Nsers).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Objps).IsUnicode(false);
            entity.Property(e => e.Sigla).IsUnicode(false);
            entity.Property(e => e.Ssins).IsUnicode(false);
            entity.Property(e => e.Ssnum).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Zzfatxt).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsPersonalDataOutrosDado>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsPersonalData_OutrosDados");

            entity.Property(e => e.Aus01).IsUnicode(false);
            entity.Property(e => e.Aus02).IsUnicode(false);
            entity.Property(e => e.Aus03).IsUnicode(false);
            entity.Property(e => e.Aus04).IsUnicode(false);
            entity.Property(e => e.Aus05).IsUnicode(false);
            entity.Property(e => e.Aus06).IsUnicode(false);
            entity.Property(e => e.Aus07).IsUnicode(false);
            entity.Property(e => e.Aus08).IsUnicode(false);
            entity.Property(e => e.Aus09).IsUnicode(false);
            entity.Property(e => e.Aus10).IsUnicode(false);
            entity.Property(e => e.Aus11).IsUnicode(false);
            entity.Property(e => e.Aus12).IsUnicode(false);
            entity.Property(e => e.Aus13).IsUnicode(false);
            entity.Property(e => e.Aus14).IsUnicode(false);
            entity.Property(e => e.Aus15).IsUnicode(false);
            entity.Property(e => e.Aus16).IsUnicode(false);
            entity.Property(e => e.Aus17).IsUnicode(false);
            entity.Property(e => e.Aus18).IsUnicode(false);
            entity.Property(e => e.Aus19).IsUnicode(false);
            entity.Property(e => e.Aus20).IsUnicode(false);
            entity.Property(e => e.DataFim).IsUnicode(false);
            entity.Property(e => e.DataIni).IsUnicode(false);
            entity.Property(e => e.DescSub).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Subty).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.ZzIndig).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsPersonalDataPessoai>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsPersonalData_Pessoais");

            entity.Property(e => e.Apelido).IsUnicode(false);
            entity.Property(e => e.ConcelhoNat).IsUnicode(false);
            entity.Property(e => e.ConcnascDesc).IsUnicode(false);
            entity.Property(e => e.DataEstCivil).IsUnicode(false);
            entity.Property(e => e.DistnascDesc).IsUnicode(false);
            entity.Property(e => e.DistritoNat).IsUnicode(false);
            entity.Property(e => e.DtFalec).IsUnicode(false);
            entity.Property(e => e.DtNasci).IsUnicode(false);
            entity.Property(e => e.EstCivil).IsUnicode(false);
            entity.Property(e => e.EstadocivilDesc).IsUnicode(false);
            entity.Property(e => e.FregnascDesc).IsUnicode(false);
            entity.Property(e => e.FreguesiaNat).IsUnicode(false);
            entity.Property(e => e.Idade).IsUnicode(false);
            entity.Property(e => e.Idade31dezembro).IsUnicode(false);
            entity.Property(e => e.Nacionalidade1).IsUnicode(false);
            entity.Property(e => e.Nacionalidade2).IsUnicode(false);
            entity.Property(e => e.Nacionalidade3).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Nome).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.PaisNat).IsUnicode(false);
            entity.Property(e => e.PaisnascDesc).IsUnicode(false);
            entity.Property(e => e.Rufnm).IsUnicode(false);
            entity.Property(e => e.Sexo).IsUnicode(false);
            entity.Property(e => e.SexoDesc).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsRemunData>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsRemun_Datas");

            entity.Property(e => e.Data).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.TipoData).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsRemunHeader>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsRemun_Header");

            entity.Property(e => e.CodGrPostos).IsUnicode(false);
            entity.Property(e => e.DescGrPostos).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsRemunRemun>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsRemun_Remun");

            entity.Property(e => e.Begda).IsUnicode(false);
            entity.Property(e => e.Betxx).IsUnicode(false);
            entity.Property(e => e.Diferencial).IsUnicode(false);
            entity.Property(e => e.Lgaxx).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Waers).IsUnicode(false);
            entity.Property(e => e.Zzposr).IsUnicode(false);
        });

        modelBuilder.Entity<ZhrWsSigreDadosComunicaco>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsSigre_DadosComunicacoes");

            entity.Property(e => e.Emailext).IsUnicode(false);
            entity.Property(e => e.Emailint).IsUnicode(false);
            entity.Property(e => e.Grupo).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsSigreDadosEndereco>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsSigre_DadosEndereco");

            entity.Property(e => e.Concelhoresid).IsUnicode(false);
            entity.Property(e => e.Cpostal).IsUnicode(false);
            entity.Property(e => e.Descpostal).IsUnicode(false);
            entity.Property(e => e.Distritoresid).IsUnicode(false);
            entity.Property(e => e.Freguesiaresid).IsUnicode(false);
            entity.Property(e => e.Grupo).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Paisresid).IsUnicode(false);
            entity.Property(e => e.Porta).IsUnicode(false);
            entity.Property(e => e.Rua).IsUnicode(false);
            entity.Property(e => e.Tiporesid).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsSigreDadosFamiliare>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsSigre_DadosFamiliares");

            entity.Property(e => e.ApelidoMae).IsUnicode(false);
            entity.Property(e => e.ApelidoPai).IsUnicode(false);
            entity.Property(e => e.Grupo).IsUnicode(false);
            entity.Property(e => e.NomeproprioMae).IsUnicode(false);
            entity.Property(e => e.NomeproprioPai).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsSigreDadosIdentificacao>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsSigre_DadosIdentificacao");

            entity.Property(e => e.Arquivo).IsUnicode(false);
            entity.Property(e => e.Dtemissao).IsUnicode(false);
            entity.Property(e => e.Dtvalidade).IsUnicode(false);
            entity.Property(e => e.Grupo).IsUnicode(false);
            entity.Property(e => e.Nii).IsUnicode(false);
            entity.Property(e => e.Nim).IsUnicode(false);
            entity.Property(e => e.Nip).IsUnicode(false);
            entity.Property(e => e.Numdocid).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Tipodoc).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsSigreDadosPessoai>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsSigre_DadosPessoais");

            entity.Property(e => e.Apelido).IsUnicode(false);
            entity.Property(e => e.Concelhonat).IsUnicode(false);
            entity.Property(e => e.Distritonat).IsUnicode(false);
            entity.Property(e => e.Dtnascimento).IsUnicode(false);
            entity.Property(e => e.Freguesianat).IsUnicode(false);
            entity.Property(e => e.Grupo).IsUnicode(false);
            entity.Property(e => e.Nome).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Paisnat).IsUnicode(false);
            entity.Property(e => e.Sexo).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsTemposServicosTempo>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWsTemposServicos_Tempos");

            entity.Property(e => e.Anos).IsUnicode(false);
            entity.Property(e => e.DataRef).IsUnicode(false);
            entity.Property(e => e.Desctxt).IsUnicode(false);
            entity.Property(e => e.Dias).IsUnicode(false);
            entity.Property(e => e.Meses).IsUnicode(false);
            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.Tipo).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ZhrWsgetPernr>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ZhrWSGetPernr");

            entity.Property(e => e.Ni).IsUnicode(false);
            entity.Property(e => e.Numsap).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}