name: Lint, Build and Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.10.x'

      - name: Install dependencies
        run: npm ci

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Build (No incremental)
        run: dotnet build --no-incremental

      - name: Check for vulnerable NuGet packages
        run: dotnet list package --vulnerable --include-transitive --no-restore

      - name: Test with dotnet CLI
        run: dotnet test --no-build
