name: Deploy .NET App with Docker Compose

on:
  push:
    tags:
      - '*'
env:
  RUNNER_TOOL_CACHE: /toolcache

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}

      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        env:
          GITEA_REF: ${{ gitea.ref }}
        with:
          host: ${{ vars.PAAS_01_HOST }}
          username: ${{ secrets.PAAS_01_USERNAME }}
          key: ${{ secrets.PAAS_01_SSH_PVT_KEY }}
          envs: GITEA_REF
          script: |
            docker login ${{ vars.REGISTRY_SERVER }} -u {{ vars.USERNAME }} -p ${{ secrets.PACKAGE_UPLOAD_TOKEN }}
            TAG="${GITEA_REF##refs/tags/v}" docker compose --project-directory ~/projects/sigdn-rh-stagging up --build --force-recreate --detach
