name: Post Merge SonarQube Scan

on:
  push:
    branches:
      - master

env:
  RUNNER_TOOL_CACHE: /toolcache

jobs:
  post-merge-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Install SonarQube scanner and dotnet-coverage
        shell: bash
        run: |
          mkdir -p .sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
          dotnet tool update dotnet-coverage --tool-path ./.sonar/coverage

      - name: Restore tools
        run: dotnet tool restore

      - name: Begin SonarQube Analysis
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin \
          /key:pessoas-integracao \
          /n:"Plataforma de Integração de Pessoas" \
          /d:sonar.token="${{ secrets.SONARQUBE_CI_TOKEN }}" \
          /d:sonar.host.url="${{ vars.SONAR_HOST_URL }}" \
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml \
          /d:sonar.exclusions="**/.devcontainer/**,**/Migrations/**,**/bin/**,**/obj/**,**/Generated/**" \
          /d:sonar.scanner.scanAll=false

      - name: Build
        run: dotnet build --no-incremental

      - name: Run tests with coverage for SonarQube
        run: |
          dotnet dotnet-coverage collect "dotnet test" \
              -f xml \
              -o coverage.xml

      - name: End SonarQube Analysis
        run: ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{  secrets.SONARQUBE_CI_TOKEN }}"
