name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.10.x'

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          DOCKER_REGISTRY_USER: ${{ vars.RELEASE_BOT_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.RELEASE_BOT_TOKEN }}
        run: npx semantic-release
