name: Security SCA Scan

on:
  pull_request:
    branches:
      - master

jobs:
  trivy-scan:
    name: Trivy Code Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          token-setup-trivy: ${{ secrets.GH_PAT }}
          scanners: 'vuln,secret'
          severity: 'MEDIUM,CRITICAL,HIGH'
          skip-dirs: 'bin,obj,.git'
          ignore-unfixed: 'true'
          timeout: '10m'
          exit-code: '1'

  notify-success:
    name: All Scans Passed
    runs-on: ubuntu-latest
    needs: [trivy-scan]
    if: success()
    steps:
      - run: echo "✅ No HIGH or CRITICAL vulnerabilities found!"
