<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DatabaseSchemaReader" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit.v3.extensibility.core" />
    <PackageReference Include="Verify.XunitV3" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference
      Include="..\..\src\Pessoas.Integracao.Analitica\Pessoas.Integracao.Analitica.csproj" />
    <ProjectReference Include="..\..\src\Pessoas.Integracao.Core\Pessoas.Integracao.Core.csproj" />  
    <ProjectReference Include="../../src/Pessoas.Integracao.Sync/Pessoas.Integracao.Sync.csproj" />
  </ItemGroup>
</Project>