<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Pessoas.Integracao-0ecd968f-7109-4ac0-985f-016de73c582b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application/" />
    <Folder Include="Domain/Entities/" />
    <Folder Include="Domain/Enums/" />
    <Folder Include="Domain/ValueObjects/" />
    <Folder Include="Infrastructure/" />
    <Folder Include="Infrastructure/Data/" />
  </ItemGroup>
</Project>
