# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Project Config
version: 1.0.0
schema: v1
models:
  - name: Zacuto
    provider: openai
    model: Zacuto-Cyber

    apiBase: http://hpc-n-1.marinha.pt:5000/v1 # Change the port to match your LLM
    apiKey: Zacuto-Cyber

    roles:
      - chat
      - edit
      - apply
      - autocomplete

